[project]
name = "Aufgabe_5"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "jlmci", email = ""},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
